config/routes.rb
Rails.application.routes.draw do
  get 'products/show'
  get 'welcome/index'


  post '/add_to_cart', to: "welcome#add_to_cart" 
  post '/remove_from_cart', to: "welcome#remove_from_cart" 

  get '/bucket', to: "welcome#bucket"

  post '/create_order', to: "welcome#create_order" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.all
    session[:cart] ||= {}
  end

  def add_to_cart
    session[:cart] ||= {}
    session[:cart][params[:id]] ||= 0
    session[:cart][params[:id]] += 1
    product = Product.find(params[:id])
    redirect_to root_path, notice: "#{product&.name} has added to your cart"
  end

  def remove_from_cart
    session[:cart] ||= {}
    session[:cart].delete(params[:id])
    product = Product.find(params[:id])
    redirect_to root_path, notice: "#{product&.name} removed from your cart"
  end

  def bucket; end

  def create_order 
    total_price = 0
    session[:cart].each do |product_id, quantity|
     product = Product.find(product_id) unless product_id.blank?
     total_price += quantity * product&.price
    end
    if Order.create(total_price: total_price)
      session[:cart].clear
      message = "Successfully created order"
    else
      message =  "Failed created order"
    end
    redirect_to root_path, notice: message 
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeqodeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/show.html.erb
<h1><%= @product.name %> Detail</h1>

<p>
	<strong> name: </strong> <%= @product.name %>
</p>


<p>
  <strong> description: </strong> <%= @product.description %>
</p>

<p>
  <strong> price: </strong> <%= @product.price %>
</p>

app/views/welcome/bucket.html.erb
<h1>Cart Items</h1>
<%= button_to "Place order", create_order_path %>    
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th></th> 
    </tr>
  </thead>
  <tbody>
    <% session[:cart].each do |product_id, quantity| %>
      <% product = Product.find(product_id) unless product_id.blank? %>
      <tr>
        <td><%= link_to product&.name %></td>
        <td><%= quantity %></td>
        <td><%= quantity * product&.price %></td>
        <td><%= button_to "Remove from cart", remove_from_cart_path(id: product.id) %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1>All Products</h1>
<%= link_to "View cart(#{session[:cart].count})", bucket_path %>

<% flash.each do |type, msg| %>
  <div> <%= msg %> </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= button_to "Add to cart", add_to_cart_path(id: product.id) %></td> 
      </tr>
    <% end %>
  </tbody>
</table>